### ISSUE TITLE
adding sleep time in usb-setup.sh to prevent errors due to slow USB mount

### ISSUE THREAD

**Issue by Albirew** [NicolasBernaerts/dns325-scripts#1]
Slow USB keys like in my case were not mounted at the time the script was started so script was always failing with these errors:

> ERROR - USB device has not been detected as Mass Storage
> ERROR - Fun_Plug root can't be moved to USB Key

In order to prevent that, I added `sleep 60` on line 18 in usb-setup.sh (/mnt/HD/HD_a2/.bootstrap/setup.sh)
Since it's likely to happen to other people too, I believe this should be added in the script.

**Comment by NicolasBernaerts** [comment]
Hi,

To minimize boot time, I've added a 60 sec loop every 5 sec to check if USB key is mounted.
As soon as USB key is detected, the script carries on.
Could you check if it solves your USB key mount delay ?

**Comment by Albirew** [comment]
Just saw 9ec85b6776f3f27a8c8aaf3e42a9b73d9e3367d8 , nicely done.Checking every 5 seconds with a 60s limit is way better than a static 60s wait =)
Working fine now.
